version: "3.9"
   
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    

    
  web:
    build: .   
    ports:
      - "8080:8080"
    command: gunicorn cybertek.wsgi:application -b 0.0.0.0:8080
    #command: python manage.py runserver 0.0.0.0:8000
    
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=cyber
      - POSTGRES_PASSWORD=Rudih0jen
    depends_on:
      - db
      
volumes:
    postgres_data:

