version: "3.9"
   
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DATABASE=${SQL_DATABASE}
    ports:
      - "5432:5432"
    

    
  web:
    build: .   
    ports:
      - "8000:${PORT}"
    command: ${START_SERVER}
        
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    depends_on:
      - db
      
volumes:
    postgres_data:

